{% set name = "templateflow" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/templateflow-{{ version }}.tar.gz
  sha256: d405fcb236d4909364cd05d16308f87ef3cdac460f1fbb2cb85f10686021805a

build:
  noarch: python
  entry_points:
    - templateflow = templateflow.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - nipreps-versions
    - pip
  run:
    - python >={{ python_min }}
    - pybids >=0.15.2
    - importlib-resources >=5.7
    - requests
    - tqdm

test:
  imports:
    - templateflow
  commands:
    - pip check
    - templateflow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/templateflow/python-client
  summary: TemplateFlow Python Client - TemplateFlow is the Zone of neuroimaging templates.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synchon
